version: '2'
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
services:
  puppet:
    hostname: puppetmaster
    domainname: foo.local
    dns_search: foo.local
    build: puppetmaster
    ports:
      - "8140:8140"
    volumes:
      - ./puppetmaster/conf:/etc/puppet
        # for production, in order to keep CA certificates?
        # - ./puppetmaster/var:/var/lib/puppet
      - ~/git/initr/:/srv/initr
  puppetdb:
    hostname: puppetdb
    dns_search: foo.local
    domainname: foo.local
    networks:
      default:
        aliases:
          - puppetdb.foo.local
    build: puppetdb
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./puppetdb/conf:/etc/puppetdb
  postgres:
    hostname: postgres
    domainname: foo.local
    dns_search: foo.local
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: puppetdb
      POSTGRES_PASSWORD: dbpasswd
    volumes:
      - ./postgres/trgm.sql:/docker-entrypoint-initdb.d/trgm.sql
#  client6:
#    hostname: puppetclient-squeeze
#    domainname: foo.local
#    dns_search: foo.local
#    build: puppetclient-squeeze
#    command: "true"
#  client7:
#    hostname: puppetclient-wheezy
#    domainname: foo.local
#    dns_search: foo.local
#    build: puppetclient-wheezy
#    command: "true"
#  client8:
#    hostname: puppetclient-jessie
#    domainname: foo.local
#    dns_search: foo.local
#    build: puppetclient-jessie
#    command: "true"
  client9:
    hostname: puppetclient-stretch
    domainname: foo.local
    dns_search: foo.local
    build: puppetclient-stretch
    command: "true"
